title: TFG - A. Salarich 
description: Finding the properties that differentiate thermostable laccases for their modification and application in bioremediation. 
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
baseurl: "/TFG-a_salarich-ca"
url: "https://adrichs.github.io"
